export const ALL_LANGUAGES = [
  { key: 'af', label: 'Afrikaans' }, { key: 'sq', label: 'Albanian' }, { key: 'am', label: 'Amharic' }, { key: 'ar', label: 'Arabic' },
  { key: 'hy', label: 'Armenian' }, { key: 'az', label: 'Azerbaijani' }, { key: 'eu', label: 'Basque' }, { key: 'be', label: 'Belarusian' },
  { key: 'bn', label: 'Bengali' }, { key: 'bs', label: 'Bosnian' }, { key: 'bg', label: 'Bulgarian' }, { key: 'ca', label: 'Catalan' },
  { key: 'ceb', label: 'Cebuano' }, { key: 'ny', label: 'Chichewa' }, { key: 'zh-CN', label: 'Chinese (Simplified)' }, { key: 'zh-TW', label: 'Chinese (Traditional)' },
  { key: 'co', label: 'Corsican' }, { key: 'hr', label: 'Croatian' }, { key: 'cs', label: 'Czech' }, { key: 'da', label: 'Danish' },
  { key: 'nl', label: 'Dutch' }, { key: 'en', label: 'English' }, { key: 'eo', label: 'Esperanto' }, { key: 'et', label: 'Estonian' },
  { key: 'tl', label: 'Filipino' }, { key: 'fi', label: 'Finnish' }, { key: 'fr', label: 'French' }, { key: 'fy', label: 'Frisian' },
  { key: 'gl', label: 'Galician' }, { key: 'ka', label: 'Georgian' }, { key: 'de', label: 'German' }, { key: 'el', label: 'Greek' },
  { key: 'gu', label: 'Gujarati' }, { key: 'ht', label: 'Haitian Creole' }, { key: 'ha', label: 'Hausa' }, { key: 'haw', label: 'Hawaiian' },
  { key: 'iw', label: 'Hebrew' }, { key: 'hi', label: 'Hindi' }, { key: 'hmn', label: 'Hmong' }, { key: 'hu', label: 'Hungarian' },
  { key: 'is', label: 'Icelandic' }, { key: 'ig', label: 'Igbo' }, { key: 'id', label: 'Indonesian' }, { key: 'ga', label: 'Irish' },
  { key: 'it', label: 'Italian' }, { key: 'ja', label: 'Japanese' }, { key: 'jw', label: 'Javanese' }, { key: 'kn', label: 'Kannada' },
  { key: 'kk', label: 'Kazakh' }, { key: 'km', label: 'Khmer' }, { key: 'rw', label: 'Kinyarwanda' }, { key: 'ko', label: 'Korean' },
  { key: 'ku', label: 'Kurdish (Kurmanji)' }, { key: 'ky', label: 'Kyrgyz' }, { key: 'lo', label: 'Lao' }, { key: 'la', label: 'Latin' },
  { key: 'lv', label: 'Latvian' }, { key: 'lt', label: 'Lithuanian' }, { key: 'lb', label: 'Luxembourgish' }, { key: 'mk', label: 'Macedonian' },
  { key: 'mg', label: 'Malagasy' }, { key: 'ms', label: 'Malay' }, { key: 'ml', label: 'Malayalam' }, { key: 'mt', label: 'Maltese' },
  { key: 'mi', label: 'Maori' }, { key: 'mr', label: 'Marathi' }, { key: 'mn', label: 'Mongolian' }, { key: 'my', label: 'Myanmar (Burmese)' },
  { key: 'ne', label: 'Nepali' }, { key: 'no', label: 'Norwegian' }, { key: 'or', label: 'Odia (Oriya)' }, { key: 'ps', label: 'Pashto' },
  { key: 'fa', label: 'Persian' }, { key: 'pl', label: 'Polish' }, { key: 'pt', label: 'Portuguese' }, { key: 'pa', label: 'Punjabi' },
  { key: 'ro', label: 'Romanian' }, { key: 'ru', label: 'Russian' }, { key: 'sm', label: 'Samoan' }, { key: 'gd', label: 'Scots Gaelic' },
  { key: 'sr', label: 'Serbian' }, { key: 'st', label: 'Sesotho' }, { key: 'sn', label: 'Shona' }, { key: 'sd', label: 'Sindhi' },
  { key: 'si', label: 'Sinhala' }, { key: 'sk', label: 'Slovak' }, { key: 'sl', label: 'Slovenian' }, { key: 'so', label: 'Somali' },
  { key: 'es', label: 'Spanish' }, { key: 'su', label: 'Sundanese' }, { key: 'sw', label: 'Swahili' }, { key: 'sv', label: 'Swedish' },
  { key: 'tg', label: 'Tajik' }, { key: 'ta', label: 'Tamil' }, { key: 'tt', label: 'Tatar' }, { key: 'te', label: 'Telugu' },
  { key: 'th', label: 'Thai' }, { key: 'tr', label: 'Turkish' }, { key: 'tk', label: 'Turkmen' }, { key: 'uk', label: 'Ukrainian' },
  { key: 'ur', label: 'Urdu' }, { key: 'ug', label: 'Uyghur' }, { key: 'uz', label: 'Uzbek' }, { key: 'vi', label: 'Vietnamese' },
  { key: 'cy', label: 'Welsh' }, { key: 'xh', label: 'Xhosa' }, { key: 'yi', label: 'Yiddish' }, { key: 'yo', label: 'Yoruba' },
  { key: 'zu', label: 'Zulu' }
];
