services:
  - type: web
    name: seal-hackathon-be
    runtime: docker
    rootDir: seal-hackathon-be
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: SEAL.API
      - key: Jwt__Audience
        value: SEAL.API.Users
      - key: Jwt__ExpireDays
        value: "7"
      - key: Auth__CookieSameSite
        value: None
      - key: AdminBootstrap__Enabled
        value: "false"
      - key: Cors__AllowedOrigins__0
        sync: false
      - key: Email__Smtp__Host
        value: smtp.gmail.com
      - key: Email__Smtp__Port
        value: "587"
      - key: Email__Smtp__EnableSsl
        value: "true"
      - key: Email__Smtp__Username
        sync: false
      - key: Email__Smtp__Password
        sync: false
      - key: Email__Smtp__FromEmail
        sync: false
      - key: Email__Smtp__FromName
        value: SEAL Hackathon
